#!/usr/bin/env python3
"""Check WIP limits and suggest scheduling deferrals (read-only, no auto task changes)."""

from __future__ import annotations

import argparse
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

try:
    import yaml
except ImportError as exc:  # pragma: no cover
    raise SystemExit("PyYAML is required. Run: pip install -r requirements.txt") from exc

DEFAULT_POLICY = "config/wip_limit_policy.yaml"
PRIORITY_RANK = {"high": 0, "medium": 1, "low": 2}


def load_yaml(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as handle:
        return yaml.safe_load(handle) or {}


def dump_status(path: Path, data: dict[str, Any]) -> None:
    header = (
        "# WIP limit status (scheduling suggestions only).\n"
        "# Generated by scripts/check_wip_limit.py — HumanOwner decides deferrals.\n"
    )
    body = yaml.safe_dump(data, allow_unicode=True, sort_keys=False, default_flow_style=False)
    path.write_text(header + body, encoding="utf-8")


def count_statuses(policy: dict[str, Any]) -> set[str]:
    limits = policy.get("limits", {})
    statuses = limits.get("count_statuses", ["in_progress", "active"])
    return {str(s).lower() for s in statuses}


def active_tasks(queue: dict[str, Any], count_statuses: set[str]) -> list[dict[str, Any]]:
    tasks: list[dict[str, Any]] = []
    for task in queue.get("tasks", []):
        status = str(task.get("status", "")).lower()
        if status in count_statuses or task.get("is_active") is True and status not in {"done", "cancelled", "deferred"}:
            if status in count_statuses:
                tasks.append(task)
    return tasks


def priority_rank(task: dict[str, Any]) -> int:
    priority = str(task.get("priority", "medium")).lower()
    return PRIORITY_RANK.get(priority, 1)


def per_project_counts(tasks: list[dict[str, Any]]) -> dict[str, int]:
    counts: dict[str, int] = {}
    for task in tasks:
        pid = str(task.get("project_id", "unknown"))
        counts[pid] = counts.get(pid, 0) + 1
    return counts


def suggest_deferrals(
    tasks: list[dict[str, Any]],
    *,
    max_wip: int,
    max_per_project: int,
) -> list[dict[str, Any]]:
    if len(tasks) <= max_wip:
        over_project = [
            {"task_id": t.get("task_id"), "project_id": t.get("project_id"), "reason": "per_project_limit"}
            for t in tasks
            if per_project_counts(tasks).get(str(t.get("project_id")), 0) > max_per_project
        ]
        if not over_project:
            return []
        sorted_tasks = sorted(tasks, key=priority_rank, reverse=True)
        return [
            {
                "task_id": t.get("task_id"),
                "project_id": t.get("project_id"),
                "priority": t.get("priority"),
                "suggested_action": "defer",
                "reason": "per_project_limit_exceeded",
            }
            for t in sorted_tasks[max_per_project:]
            if per_project_counts([x for x in tasks if str(x.get("project_id")) == str(t.get("project_id"))]) > max_per_project
        ][: max(0, len(tasks) - max_wip)]

    sorted_tasks = sorted(tasks, key=priority_rank, reverse=True)
    excess = len(tasks) - max_wip
    defer_candidates = sorted_tasks[:excess]
    return [
        {
            "task_id": t.get("task_id"),
            "project_id": t.get("project_id"),
            "priority": t.get("priority"),
            "suggested_action": "defer",
            "reason": "portfolio_wip_limit_exceeded",
        }
        for t in defer_candidates
    ]


def build_payload(queue: dict[str, Any], portfolio: dict[str, Any], policy: dict[str, Any]) -> dict[str, Any]:
    limits = policy.get("limits", {})
    max_wip = int(limits.get("max_concurrent_in_progress", 2))
    max_per_project = int(limits.get("max_concurrent_per_project", 1))
    statuses_to_count = count_statuses(policy)

    tasks = active_tasks(queue, statuses_to_count)
    portfolio_wip = int((portfolio.get("summary") or {}).get("current_wip", 0))
    effective_wip = max(len(tasks), portfolio_wip)
    over_limit = effective_wip > max_wip
    per_project = per_project_counts(tasks)
    per_project_violations = {pid: c for pid, c in per_project.items() if c > max_per_project}
    deferrals = suggest_deferrals(tasks, max_wip=max_wip, max_per_project=max_per_project) if over_limit or per_project_violations else []

    return {
        "schema_version": "0.1.0",
        "generated_at": datetime.now(timezone.utc).replace(microsecond=0).isoformat(),
        "limits": {
            "max_concurrent_in_progress": max_wip,
            "max_concurrent_per_project": max_per_project,
        },
        "summary": {
            "queue_in_progress_count": len(tasks),
            "portfolio_current_wip": portfolio_wip,
            "effective_wip": effective_wip,
            "over_limit": over_limit or bool(per_project_violations),
            "deferral_suggestions": len(deferrals),
        },
        "per_project_counts": per_project,
        "per_project_violations": per_project_violations,
        "deferral_suggestions": deferrals,
        "scheduling_note": "Suggestions only — update governance_task_queue manually after HumanOwner review.",
    }


def render_report(payload: dict[str, Any]) -> str:
    summary = payload.get("summary", {})
    lines = [
        "# WIP Limit & Scheduling",
        "",
        f"- generated_at: {payload.get('generated_at')}",
        f"- max_concurrent_in_progress: {payload.get('limits', {}).get('max_concurrent_in_progress')}",
        f"- effective_wip: {summary.get('effective_wip')}",
        f"- over_limit: {summary.get('over_limit')}",
        f"- deferral_suggestions: {summary.get('deferral_suggestions')}",
        "",
    ]
    if payload.get("deferral_suggestions"):
        lines.append("## Suggested Deferrals")
        lines.append("")
        for item in payload["deferral_suggestions"]:
            lines.append(
                f"- `{item.get('task_id')}` ({item.get('project_id')}, {item.get('priority')}): "
                f"{item.get('reason')} → {item.get('suggested_action')}"
            )
        lines.append("")
    lines.append("HumanOwner must approve deferrals; script does not modify task queue.")
    lines.append("")
    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Check WIP limits and suggest deferrals")
    parser.add_argument("--policy", default=DEFAULT_POLICY)
    parser.add_argument("--write", action="store_true", help="Write YAML and report files")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    root = Path(".").resolve()
    policy = load_yaml(root / args.policy)
    sources = policy.get("sources", {})
    queue_path = root / str(sources.get("governance_task_queue", "governance/governance_task_queue.yaml"))
    portfolio_path = root / str(sources.get("portfolio_state", "governance/portfolio_state.yaml"))
    output_path = root / str(sources.get("output", "governance/wip_limit_status.yaml"))
    report_path = root / str(sources.get("report", "reports/wip_limit_scheduling.md"))

    if not queue_path.exists():
        raise SystemExit(f"Task queue not found: {queue_path}")

    queue = load_yaml(queue_path)
    portfolio = load_yaml(portfolio_path) if portfolio_path.exists() else {"summary": {}}
    payload = build_payload(queue, portfolio, policy)
    report = render_report(payload)

    summary = payload["summary"]
    print(
        f"[ok] wip limit: effective_wip={summary['effective_wip']} "
        f"max={payload['limits']['max_concurrent_in_progress']} "
        f"over_limit={summary['over_limit']} deferrals={summary['deferral_suggestions']}"
    )
    if not args.write:
        print("[dry-run] files not written")
        return 0

    output_path.parent.mkdir(parents=True, exist_ok=True)
    dump_status(output_path, payload)
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(report, encoding="utf-8")
    print(f"[ok] wrote {output_path} and {report_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
