#!/usr/bin/env python3
"""Build review_queue proposals for project_rule promotion (never auto-merge by default)."""

from __future__ import annotations

import argparse
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

try:
    import yaml
except ImportError as exc:  # pragma: no cover
    raise SystemExit("PyYAML is required. Run: pip install -r requirements.txt") from exc

DEFAULT_POLICY = "config/project_rule_promotion_policy.yaml"


def load_yaml(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as handle:
        data = yaml.safe_load(handle) or {}
    return data if isinstance(data, dict) else {}


def dump_queue(path: Path, data: dict[str, Any]) -> None:
    header = (
        "# Project rule promotion queue (review_queue proposals, HITL merge).\n"
        "# Generated by scripts/promote_project_rule.py — not merged into review_queue automatically.\n"
    )
    body = yaml.safe_dump(data, allow_unicode=True, sort_keys=False, default_flow_style=False)
    path.write_text(header + body, encoding="utf-8")


def candidate_eligible(candidate: dict[str, Any], selection: dict[str, Any]) -> bool:
    status = str(candidate.get("status", "")).lower()
    allowlist = {str(s).lower() for s in selection.get("candidate_status_allowlist", [])}
    if status not in allowlist:
        return False
    kinds = {str(k).lower() for k in selection.get("kinds", [])}
    if kinds and str(candidate.get("kind", "playbook")).lower() not in kinds:
        return False
    return True


def build_proposal(candidate: dict[str, Any], promotion: dict[str, Any], *, now: str) -> dict[str, Any]:
    candidate_id = str(candidate.get("candidate_id", "unknown"))
    project_id = str(candidate.get("project_id", "unknown"))
    task_id = str(candidate.get("source_task_id", "unknown"))
    prefix = str(promotion.get("id_prefix", "rq_promo_"))
    review_id = f"{prefix}{candidate_id.replace('playbook_', '')}"
    options = list(promotion.get("options") or ["approve_promotion", "defer", "reject"])
    return {
        "review_id": review_id,
        "type": str(promotion.get("review_type", "project_rule_promotion")),
        "project_id": project_id,
        "task_id": task_id,
        "prompt": f"是否将候选 {candidate_id} 推广为 {project_id} 的 project_rule？",
        "options": options,
        "context_refs": list(candidate.get("context_refs") or []),
        "candidate_id": candidate_id,
        "status": "pending_human_merge",
        "decision": None,
        "decided_at": None,
        "expires_at": None,
        "generated_at": now,
    }


def render_report(proposals: list[dict[str, Any]], *, dry_run: bool, merge: bool) -> str:
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    return "\n".join(
        [
            "# Project Rule Promotion Plan",
            "",
            f"- generated_at: {ts}",
            f"- proposal_count: {len(proposals)}",
            f"- mode: {'dry-run' if dry_run else 'write'}",
            f"- merge_into_review_queue: {merge}",
            "",
            "HumanOwner must merge approved items into `governance/review_queue.yaml`.",
            "",
        ]
        + [f"- {p.get('review_id')}: {p.get('candidate_id')} ({p.get('project_id')})" for p in proposals]
        + [""]
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Plan project_rule promotions for review_queue")
    parser.add_argument("--policy", default=DEFAULT_POLICY)
    parser.add_argument("--write", action="store_true")
    parser.add_argument(
        "--merge-review-queue",
        action="store_true",
        help="Explicitly append open proposals to review_queue.yaml (HITL still required to close)",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    root = Path(".").resolve()
    policy_path = root / args.policy
    if not policy_path.exists():
        print(f"[project_rule_promotion] policy missing: {policy_path}")
        return 2

    from validate_project_rule_promotion_policy import validate_project_rule_promotion_policy

    policy = load_yaml(policy_path)
    errors = validate_project_rule_promotion_policy(policy, source=policy_path.name)
    if errors:
        print(f"[project_rule_promotion] policy invalid: {errors[:3]}")
        return 2

    sources = policy.get("sources", {})
    candidates_path = root / str(sources.get("playbook_candidates", "governance/playbook_candidates.yaml"))
    if not candidates_path.exists():
        print(f"[project_rule_promotion] candidates missing: {candidates_path}")
        return 2

    registry = load_yaml(candidates_path)
    selection = policy.get("selection", {})
    promotion = policy.get("promotion", {})
    now = datetime.now(timezone.utc).replace(microsecond=0).isoformat()
    proposals = [
        build_proposal(candidate, promotion, now=now)
        for candidate in registry.get("candidates", [])
        if isinstance(candidate, dict) and candidate_eligible(candidate, selection)
    ]
    proposals.sort(key=lambda row: str(row.get("review_id", "")))

    defaults = policy.get("defaults", {})
    dry_run = not args.write and bool(defaults.get("dry_run", True))
    merge = args.merge_review_queue and bool(defaults.get("merge_into_review_queue", False))

    report_path = root / str(sources.get("report", "reports/project_rule_promotion_plan.md"))
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(render_report(proposals, dry_run=dry_run, merge=merge), encoding="utf-8")

    payload = {
        "schema_version": "0.1.0",
        "generated_at": now,
        "source_candidates": candidates_path.relative_to(root).as_posix(),
        "summary": {"total_proposals": len(proposals), "pending_human_merge": len(proposals)},
        "proposals": proposals,
    }

    if dry_run:
        print(f"[project_rule_promotion] dry-run proposals={len(proposals)} report={report_path.name}")
        return 0

    output_path = root / str(sources.get("proposal_output", "governance/project_rule_promotion_queue.yaml"))
    dump_queue(output_path, payload)

    if merge:
        rq_path = root / str(sources.get("review_queue_ref", "governance/review_queue.yaml"))
        rq = load_yaml(rq_path)
        items = list(rq.get("items", []))
        existing_ids = {str(item.get("review_id")) for item in items if isinstance(item, dict)}
        added = 0
        for proposal in proposals:
            if proposal["review_id"] in existing_ids:
                continue
            items.append(
                {
                    "review_id": proposal["review_id"],
                    "type": proposal["type"],
                    "project_id": proposal["project_id"],
                    "task_id": proposal["task_id"],
                    "prompt": proposal["prompt"],
                    "options": proposal["options"],
                    "context_refs": proposal["context_refs"],
                    "status": "open",
                    "decision": None,
                    "decided_at": None,
                    "expires_at": None,
                }
            )
            added += 1
        rq["items"] = items
        rq["updated_at"] = now
        body = yaml.safe_dump(rq, allow_unicode=True, sort_keys=False, default_flow_style=False)
        rq_path.write_text(body, encoding="utf-8")
        print(f"[project_rule_promotion] merged {added} into {rq_path.relative_to(root)}")
    else:
        print(f"[project_rule_promotion] wrote {output_path.relative_to(root)} proposals={len(proposals)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
