#!/usr/bin/env python3
"""Track per-project budget and mock model/API cost estimates (no billing API keys)."""

from __future__ import annotations

import argparse
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

try:
    import yaml
except ImportError as exc:  # pragma: no cover
    raise SystemExit("PyYAML is required. Run: pip install -r requirements.txt") from exc

DEFAULT_POLICY = "config/budget_tracking_policy.yaml"
ACTIVE_LIFECYCLES = {"active", "bootstrap", "maintenance", "idea"}


def load_yaml(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as handle:
        return yaml.safe_load(handle) or {}


def dump_tracking(path: Path, data: dict[str, Any]) -> None:
    header = (
        "# Budget & cost tracking snapshot (mock estimates when no billing API).\n"
        "# Generated by scripts/track_budget_cost.py — HumanOwner approves budget changes.\n"
    )
    body = yaml.safe_dump(data, allow_unicode=True, sort_keys=False, default_flow_style=False)
    path.write_text(header + body, encoding="utf-8")


def rate_for_agent(rates: dict[str, Any], agent: str) -> float:
    per_run = rates.get("per_agent_run", {})
    if not isinstance(per_run, dict):
        return 0.0
    value = per_run.get(agent, per_run.get("Cursor", 0.0))
    try:
        return float(value)
    except (TypeError, ValueError):
        return 0.0


def portfolio_by_id(portfolio: dict[str, Any]) -> dict[str, dict[str, Any]]:
    return {str(p.get("project_id", "")): p for p in portfolio.get("projects", [])}


def build_project_entry(
    registry_project: dict[str, Any],
    portfolio_row: dict[str, Any] | None,
    *,
    rates: dict[str, Any],
    runs_per_active: int,
    warning_pct: float,
) -> dict[str, Any]:
    project_id = str(registry_project.get("project_id", ""))
    lifecycle = str(
        (portfolio_row or {}).get("lifecycle") or registry_project.get("lifecycle", "active")
    )
    agent = str(
        (portfolio_row or {}).get("recommended_agent") or registry_project.get("default_agent", "Cursor")
    )
    monthly_budget = float(rates.get("monthly_budget_default_usd", 100.0))
    unit_cost = rate_for_agent(rates, agent)
    estimated_runs = runs_per_active if lifecycle in ACTIVE_LIFECYCLES else 0
    estimated_cost = round(unit_cost * estimated_runs, 2)
    utilization_pct = round((estimated_cost / monthly_budget * 100) if monthly_budget else 0.0, 1)
    return {
        "project_id": project_id,
        "lifecycle": lifecycle,
        "recommended_agent": agent,
        "monthly_budget_usd": monthly_budget,
        "estimated_runs": estimated_runs,
        "estimated_cost_usd": estimated_cost,
        "utilization_pct": utilization_pct,
        "budget_warning": utilization_pct >= warning_pct,
        "data_source": "mock_placeholder",
    }


def build_payload(
    registry: dict[str, Any],
    portfolio: dict[str, Any],
    policy: dict[str, Any],
) -> dict[str, Any]:
    rates = policy.get("mock_rates", {})
    estimation = policy.get("estimation", {})
    runs_per_active = int(estimation.get("runs_per_active_project", 4))
    warning_pct = float(estimation.get("warning_threshold_pct", 80))
    by_id = portfolio_by_id(portfolio)
    projects = [
        build_project_entry(
            entry,
            by_id.get(str(entry.get("project_id", ""))),
            rates=rates,
            runs_per_active=runs_per_active,
            warning_pct=warning_pct,
        )
        for entry in registry.get("projects", [])
    ]
    total_estimated = round(sum(p["estimated_cost_usd"] for p in projects), 2)
    warnings = sum(1 for p in projects if p.get("budget_warning"))
    return {
        "schema_version": "0.1.0",
        "generated_at": datetime.now(timezone.utc).replace(microsecond=0).isoformat(),
        "currency": str(rates.get("currency", "USD")),
        "data_source": str(estimation.get("data_source", "mock_placeholder")),
        "external_api_called": False,
        "summary": {
            "total_projects": len(projects),
            "total_estimated_cost_usd": total_estimated,
            "projects_with_warning": warnings,
            "portfolio_budget_warning": warnings > 0,
        },
        "projects": projects,
    }


def render_report(payload: dict[str, Any]) -> str:
    summary = payload.get("summary", {})
    lines = [
        "# Budget & Cost Tracking",
        "",
        f"- generated_at: {payload.get('generated_at')}",
        f"- data_source: {payload.get('data_source')} (no billing API keys)",
        f"- total_estimated_cost_usd: {summary.get('total_estimated_cost_usd')}",
        f"- projects_with_warning: {summary.get('projects_with_warning')}",
        "",
        "## Per-Project Estimates",
        "",
        "| project_id | agent | est. cost USD | utilization % | warning |",
        "|------------|-------|---------------|---------------|---------|",
    ]
    for p in payload.get("projects", []):
        warn = "yes" if p.get("budget_warning") else "—"
        lines.append(
            f"| {p.get('project_id')} | {p.get('recommended_agent')} | "
            f"{p.get('estimated_cost_usd')} | {p.get('utilization_pct')} | {warn} |"
        )
    lines.extend(
        [
            "",
            "HumanOwner must approve any budget increase; this report uses mock rates only.",
            "",
        ]
    )
    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Track budget and mock cost estimates")
    parser.add_argument("--policy", default=DEFAULT_POLICY)
    parser.add_argument("--write", action="store_true", help="Write YAML and report files")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    root = Path(".").resolve()
    policy = load_yaml(root / args.policy)
    sources = policy.get("sources", {})
    registry_path = root / str(sources.get("project_registry", "governance/project_registry.yaml"))
    portfolio_path = root / str(sources.get("portfolio_state", "governance/portfolio_state.yaml"))
    output_path = root / str(sources.get("output", "governance/budget_cost_tracking.yaml"))
    report_path = root / str(sources.get("report", "reports/budget_cost_tracking.md"))

    if not registry_path.exists():
        raise SystemExit(f"Registry not found: {registry_path}")

    registry = load_yaml(registry_path)
    portfolio = load_yaml(portfolio_path) if portfolio_path.exists() else {"projects": []}
    payload = build_payload(registry, portfolio, policy)
    report = render_report(payload)

    print(
        f"[ok] budget tracking: projects={payload['summary']['total_projects']} "
        f"est_cost={payload['summary']['total_estimated_cost_usd']} "
        f"warnings={payload['summary']['projects_with_warning']}"
    )
    if not args.write:
        print("[dry-run] files not written")
        return 0

    output_path.parent.mkdir(parents=True, exist_ok=True)
    dump_tracking(output_path, payload)
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(report, encoding="utf-8")
    print(f"[ok] wrote {output_path} and {report_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
